version: '3.8'
services:
  app:
    build:
      context: .
      target: build
    container_name: schedx_prod
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres
      - redis

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P!sc3s@Mongodb_$$4095

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P!sc3s@Postgresql_$4095
      POSTGRES_DB: postgres

  redis:
    image: redis:7
